// src/web/static/js/vue-components/translatable.vue
<template>
<div>
    <slot :t="t"></slot>
</div>
</template>

<script>
    let RestApi = require("../rest-api");
    module.exports = {
        data() {
            return {
                t: {}
            }
        },
        props: {
            locale: String,
            keys: Object,
            toTranslate: Object
        },
        methods: {
            async translateAll() {
                await Promise.all(Object.keys(this.toTranslate).map(async key => {
                    let mappingKey = key;
                    let translationKey = this.toTranslate[key];
                    if(!translationKey) return;

                    this.t[mappingKey] = (await RestApi.getTranslation(this.locale, translationKey, this.keys)).data;
                }));
            }
        },
        mounted() {
            this.translateAll();
        }
    };
</script>

<style>
</style>

// src/web/static/js/react-components/translatable.jsx
let React = require("react");

let RestApi = require("../rest-api.js");

class TranslationEditor extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            t: {}
        };
        this.fetchTranslations();
    }

    render() {
        return (
            <template></template>
        );
    }

    fetchTranslations = async() => {
        let translations = {};
        let locale = this.props.locale;

        if(!this.props.keys) {
            console.warn("No keys to translate provided.");
            return;
        }

        if(!locale) {
            console.warn("No locale provided, trying to fetch from session storage ...");
            locale = (await RestApi.getSessionParameter("locale")).data;
            if(!locale) {
                console.warn("No locale provided, defaulting to 'en'");
                locale = "en";
            }
        }

        await Promise.all(Object.keys(this.props.keys || {}).map(async key => {
            translations[key] = (await RestApi.getTranslation(this.props.locale || "en", this.props.keys[key])).data;
        }));

        this.setState({t: translations});
        this.props.afterUpdate && this.props.afterUpdate(this.state.t);
    }
}

module.exports = TranslationEditor;
